export const state = {
  states: [
    {
      state: "Gujarat",
      districts: [
        "AHMEDABAD CORPORATION (CITY)",
        "AHMEDABAD (RURAL)",
        "AMRELI",
        "ANAND",
        "ARAVALLI",
        "BANASKANTHA",
        "BHARUCH",
        "BHAVNAGAR (RURAL)",
        "BHAVNAGAR CORPORATION (CITY)",
        "BOTAD",
        "CHHOTA UDEPUR",
        "DAHOD",
        "DANGS",
        "DEVBHOOMI DWARKA",
        "GANDHINAGAR",
        "GIR SOMNATH",
        "JAMNAGAR",
        "JUNAGADH",
        "KUTCH",
        "KHEDA",
        "MAHISAGAR",
        "MEHSANA",
        "MORBI",
        "NARMADA",
        "NAVSARI",
        "PANCHMAHAL",
        "PATAN",
        "PORBANDAR",
        "RAJKOT CORPORATION (CITY)",
        "RAJKOT (RURAL)",
        "SABARKANTHA",
        "SURAT",
        "SURENDRANAGAR",
        "TAPI",
        "VADODARA",
        "VALSAD",
      ],
    },
  ],
};
